### ISSUE TITLE
Multus CNI does not work for v4.0.0.

### ISSUE THREAD

**Issue by ScionOfDesign** [startechnica/apps#33]
Hello, I just tried installing your Multus CNI helm chart and noticed that I got the following error when trying to use image v4.0.0:
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "cp": executable file not found in $PATH: unknown
Back-off restarting failed container
```

The Multus DaemonSet started up fine when using v3.9.3.

**Comment by firmansyahn** [comment]
Thank you for using this chart.
I update the chart to support Multus CNI v4.0.2 with Thick Plugin.

Have a good day.
