### ISSUE TITLE
netbox: external-db.yaml missing a "."

### ISSUE THREAD

**Issue by lg0killer** [startechnica/apps#71]
I made a note [here](https://github.com/startechnica/apps/commit/5788f62b8f76db26f96ec5a6200d4e550c402698)

The include for the netbox.databasePassword seems to be missing a "." thus leaving you with this error message:
`Error: template: netbox/templates/Secret/external-db.yaml:13:57: executing "netbox/templates/Secret/external-db.yaml" at <include>: wrong number of args for include: want 2 got 1`

**Comment by lg0killer** [comment]
Attached to https://github.com/startechnica/apps/pull/72

**Comment by firmansyahn** [comment]
Thank you for your notice, hope v[5.0.10](https://github.com/startechnica/apps/releases/tag/netbox-5.0.10) fixed it for good.
